### PR TITLE
dsl: exit 1 when there are failures.

### LINKED ISSUE #67: Return non-zero when `$ brew bundle` fails
When running `brew bundle` now, if a package fails to install, the command still returns `0`. It would be awesome if the command returned `1` or some other non-zero value whenever it encounters an error.

For example, given the following Brewfile:

```
# Brewfile
brew 'node'
brew 'some-package-that-doesnt-exist'
```

```
$ brew bundle
Succeed to install node
Error: No available formula for some-package-that-doesnt-exist 
Searching formulae...
Searching taps...
Fail to install some-package-that-doesnt-exist

Success: 1 Fail: 1

$ echo $?
0
```

### PR DESCRIPTION
**Pull request by mikemcquaid**
Closes #67.

### CODE REVIEW

File: lib/bundle/dsl.rb [hunk 1]
```diff
@@ -55,6 +55,7 @@ def install
         end
       end
       puts "\nSuccess: #{success} Fail: #{fail}"
+      exit 1 if fail > 0
```
Comment (xu-cheng) [inline lib/bundle/dsl.rb]: Maybe return false and exit at `Bundle::Commands#Install::run`? Your call.

Comment (mikemcquaid) [inline lib/bundle/dsl.rb]: Cool.

Comment (mikemcquaid) [inline lib/bundle/dsl.rb]: Updated.

File: lib/bundle/commands/install.rb [hunk 2]
```diff
@@ -1,7 +1,9 @@
 module Bundle::Commands
   class Install
     def self.run
-      Bundle::Dsl.new(Bundle.brewfile).install
+      success = Bundle::Dsl.new(Bundle.brewfile).install
+      exit 1 unless success
+      success
```
Comment (xu-cheng) [inline lib/bundle/commands/install.rb]: How about: `exit 1 unless Bundle::Dsl.new(Bundle.brewfile).install`?

Comment (mikemcquaid) [inline lib/bundle/commands/install.rb]: I never like having the actual action being part of the `if` or `unless` personally. What do you think?

Comment (xu-cheng) [inline lib/bundle/commands/install.rb]: How about `Bundle::Dsl.new(Bundle.brewfile).install || exit 1`?

IMHO, it's pointless to return `success` here. As it will always be true.
