### PR TITLE
cask_dumper: handle languages.

### LINKED ISSUE #891: brew bundle dump failed
I just got the following error messages today and have no idea what's going on.

```
$ brew bundle dump
Error: undefined method `sub' for ["zh-TW"]:Array
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:45:in `block in dump_cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:44:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:44:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:44:in `dump_cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:36:in `block in dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:35:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/cask_dumper.rb:35:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:20:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:32:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

Here comes my `brew config`:

```
$ brew config
HOMEBREW_VERSION: 2.7.6-11-g5b2f8a5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5b2f8a5a7307b58843eedfb2886a80964b937b30
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1fe981399a12641c22ac4860928e762c1d61236c
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.GL7lz2dMD9/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2
macOS: 10.15.7-x86_64
CLT: 12.0.32.28
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Fixes #891

### CODE REVIEW

File: lib/bundle/cask_dumper.rb [hunk 1]
```diff
@@ -41,8 +41,14 @@ def dump(casks_required_by_formulae, describe: false)
...
-        cask.config.explicit.map do |k, v|
-          "#{k}: \"#{v.sub(/^#{ENV['HOME']}/, "~")}\""
+        # TODO: replace this logic with an actual call in Library/Homebrew/cask/
+        cask.config.explicit.map do |key, value|
+          if key == "language"
+            key = "languages"
+            value = value.split(",")
+          end
+
+          "#{key}: \"#{value.sub(/^#{ENV['HOME']}/, "~")}\""
```
Comment (MikeMcQuaid) [inline lib/bundle/cask_dumper.rb:51]: @EricFromCanada Would you be able to take a look at that? CC @Homebrew/cask for help either doing this or a pointer to what the best methods would be to call to avoid this duplication here.

Comment (EricFromCanada) [reply lib/bundle/cask_dumper.rb]: Something like this? Homebrew/brew#10462
