### PR TITLE
Don't get full cask name when dumping casks

### LINKED ISSUE #866: brew bundle doesn't handle external taps correctly
After PR #864 was merged, `brew bundle` doesn't handle external taps correctly, and always wants to install (or uninstall for `cleanup`) external taps.

Steps to reproduce:
```
$ cat Brewfile-test
tap "jabenninghoff/edge"
cask "jabenninghoff/edge/transcriptions"

$ brew bundle --file Brewfile-test install
Installing transcriptions
Homebrew Bundle complete! 1 Brewfile dependency now installed.

$ brew bundle check --file Brewfile-test
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
```

I expected the `brew bundle check` to note that the Brewfile dependencies are satisfied.

This also affects `brew clean` which always wants to remove casks from external taps.

### PR DESCRIPTION
**Pull request by Tyrubias**
When I switched to using `Cask::Caskroom` to get installed casks, I got the full name of the Cask (including the tap name, if any) instead of just the token. This PR should emulate the old behavior.

Fixes #866

### CODE REVIEW

File: spec/bundle/dumper_spec.rb [hunk 1]
```diff
@@ -16,8 +16,8 @@
     Bundle::WhalebrewDumper.reset!
     Bundle::BrewServices.reset!
 
-    chrome = instance_double("Cask::Cask", full_name: "google-chrome")
-    java = instance_double("Cask::Cask", full_name: "java")
+    chrome = instance_double("Cask::Cask", to_s: "google-chrome")
+    java = instance_double("Cask::Cask", to_s: "java")
```
Comment (jacobbednarz) [inline spec/bundle/dumper_spec.rb:20]: As we identified a regression from a previous change, I'd think we would want to add a test case covering that scenario. Thoughts?

Comment (Tyrubias) [reply spec/bundle/dumper_spec.rb:20]: Seems like a good idea. Would that involve adding a double that's a cask from a tap? I'll think about how to implement that.

Comment (Tyrubias) [reply spec/bundle/dumper_spec.rb]: I added a test case but I don't think it's actually useful. Could I have some advice on a good way to test this?

Comment (jacobbednarz) [reply spec/bundle/dumper_spec.rb]: Which part don't you don't is useful?

File: spec/bundle/dumper_spec.rb [hunk 2]
```diff
@@ -16,15 +16,16 @@
     Bundle::WhalebrewDumper.reset!
     Bundle::BrewServices.reset!
 
-    chrome = instance_double("Cask::Cask", full_name: "google-chrome")
-    java = instance_double("Cask::Cask", full_name: "java")
+    chrome = instance_double("Cask::Cask", full_name: "google-chrome", to_s: "google-chrome")
+    java = instance_double("Cask::Cask", full_name: "java", to_s: "java")
+    iterm2beta = instance_double("Cask::Cask", full_name: "homebrew/cask-versions/iterm2-beta", to_s: "iterm2-beta")
```
Comment (jacobbednarz) [inline spec/bundle/dumper_spec.rb:21]: I'm not sure if this is the correct assertion as the issue we're having is with things like `cask "some/external/cask"` listed in the Brewfile ([example](https://github.com/jacobbednarz/j/blob/main/config/homebrew/Brewfile#L197)). I'm not entirely positive this solves the issue.

Comment (Tyrubias) [reply spec/bundle/dumper_spec.rb:21]: In this case shouldn't I be checking a cask whose full name does include the tap and asserting that the output Brewfile doesn't contain one?

**Comment by MikeMcQuaid** [comment]
Thanks again @Tyrubias!

File: spec/bundle/dumper_spec.rb (hunk 2 above)
Comment (MikeMcQuaid) [reply spec/bundle/dumper_spec.rb:21]: Looks right to me 👍🏻

Comment (jacobbednarz) [reply spec/bundle/dumper_spec.rb:21]: Thanks for confirming!
